// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/buttons": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新按钮，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "按钮管理"
                ],
                "parameters": [
                    {
                        "description": "按钮信息",
                        "name": "button",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "按钮创建成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "创建按钮失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/buttons/menu/{menuId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定菜单的所有按钮列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "按钮管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "menuId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "按钮列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Button"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的菜单ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取按钮列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/buttons/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定按钮的信息，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "按钮管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "按钮ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "按钮信息",
                        "name": "button",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "按钮信息更新成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "更新按钮信息失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/buttons/{id}/permission": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定按钮绑定权限，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "按钮管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "按钮ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "权限信息",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限绑定成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "绑定权限失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/buttons/{id}/permissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定按钮的权限列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "按钮管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "按钮ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的按钮ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取按钮权限列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "用户登录接口，验证用户名和密码，返回JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回token",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/menus": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有菜单的列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "responses": {
                    "200": {
                        "description": "菜单列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Menu"
                            }
                        }
                    },
                    "500": {
                        "description": "获取菜单列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新菜单，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "parameters": [
                    {
                        "description": "菜单信息",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "菜单创建成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "创建菜单失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/menus/parent/{parentId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定父级菜单的子菜单列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父级菜单ID",
                        "name": "parentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "子菜单列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Menu"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的父级菜单ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取子菜单列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/menus/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定菜单的信息，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "菜单信息",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "菜单信息更新成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "更新菜单信息失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/menus/{id}/permission": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定菜单绑定权限，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "权限信息",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限绑定成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "绑定权限失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/menus/{id}/permissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定菜单的权限列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的菜单ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取菜单权限列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/permissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有权限的列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "responses": {
                    "200": {
                        "description": "权限列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "500": {
                        "description": "获取权限列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新权限，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "parameters": [
                    {
                        "description": "权限信息",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "权限创建成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "创建权限失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/permissions/type/{type}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定类型的所有权限列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "权限类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "500": {
                        "description": "获取权限列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/permissions/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定权限的信息，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "权限ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "权限信息",
                        "name": "permission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限信息更新成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "更新权限信息失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有角色的列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "responses": {
                    "200": {
                        "description": "角色列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Role"
                            }
                        }
                    },
                    "500": {
                        "description": "获取角色列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新角色，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "角色创建成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "创建角色失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/roles/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定角色的信息，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "角色信息更新成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "更新角色信息失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/roles/{id}/permissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定角色的所有权限列表，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的角色ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取角色权限列表失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定角色绑定一个或多个权限，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "权限ID列表",
                        "name": "permissionIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限绑定成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "绑定权限失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新用户，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "用户创建成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "创建用户失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/users/routes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户的路由数据，包括菜单和权限信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "responses": {
                    "200": {
                        "description": "路由数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.RouteItem"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的用户ID",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "获取路由数据失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定用户的信息，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息更新成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "更新用户信息失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/users/{id}/roles": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定用户绑定一个或多个角色，需要管理员权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色ID列表",
                        "name": "roleIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "角色绑定成功",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "绑定角色失败",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Button": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "create"
                },
                "code": {
                    "type": "string",
                    "example": "create"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "menu_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "创建用户"
                },
                "permission_code": {
                    "type": "string",
                    "example": "user:create"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Menu": {
            "type": "object",
            "properties": {
                "button_association": {
                    "type": "boolean",
                    "example": false
                },
                "component": {
                    "type": "string",
                    "example": "@/views/system/index"
                },
                "created_at": {
                    "type": "string"
                },
                "icon": {
                    "type": "string",
                    "example": "setting"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_visible": {
                    "type": "boolean",
                    "example": true
                },
                "meta": {
                    "$ref": "#/definitions/models.MenuMeta"
                },
                "name": {
                    "type": "string",
                    "example": "系统管理"
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "parent_id": {
                    "type": "integer",
                    "example": 0
                },
                "path": {
                    "type": "string",
                    "example": "/system"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.MenuMeta": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "button_id": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "menu_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "查看仪表盘"
                },
                "permission_code": {
                    "type": "string",
                    "example": "view_dashboard"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "menu"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "系统管理员角色"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "管理员"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Permission"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "services.RouteItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.RouteItem"
                    }
                },
                "component": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/services.RouteMeta"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "services.RouteMeta": {
            "type": "object",
            "properties": {
                "activeIcon": {
                    "type": "string"
                },
                "authority": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "darkIcon": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "租户中心API",
	Description:      "租户中心系统的API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
